name: Generate config
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Set variables
      run: |
        echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
        echo "fake_ip_filter=https://raw.githubusercontent.com/juewuy/ShellCrash/dev/public/fake_ip_filter.list" >> $GITHUB_ENV
      shell: bash

    - name: Generate fakeip-user.yaml
      run: |
        mkdir -p ./tmp/ ./clash/ ./sing-box/
        cat <<EOF > ./clash/fakeip-user.yaml
        sniffer:
          enable: true
          parse-pure-ip: true
          sniff: {HTTP: {ports: [80, 8080-8880], TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}}
          skip-domain: ['Mijia Cloud']

        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
            - '*'
        EOF
        curl -sSL ${fake_ip_filter} | grep -v '#' | sed '/^\s*$/d' | sed "s/.*/'&'/" | sed 's/^/    - /' >> ./clash/fakeip-user.yaml
        cat <<EOF >> ./clash/fakeip-user.yaml
          nameserver:
            - 'https://223.5.5.5/dns-query#h3=true'
            - https://1.12.12.12/dns-query
        EOF

    - name: Release and upload `clash` assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: clash
        tag: clash
        overwrite: true
        body: "[Clash](https://github.com/Dreamacro/clash) 配置文件"
        file_glob: true
        file: ./clash/*

    - name: Git push assets to "clash" branch
      run: |
        cd ./clash/ || exit 1
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b clash
        git add .
        git commit -m "Clash 配置文件更新于 ${update_version}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin clash

    - name: Purge jsDelivr CDN
      run: |
        cd ./clash/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@clash/${file}"
        done

    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 3
        keep_minimum_runs: 1
